### ISSUE TITLE
Why do you hate vuejs?

### ISSUE THREAD

**Issue by junaga** [fireship-io/10-javascript-frameworks#3]
I think the movement is insane. You bet on angular, and it has little adoption. Who cares? You should be able to use **any tool**, who cares what people think. Give it a try! I am a total noob, and your videos quite literally run our company. I absolutely love Firebase, and your channel. Am a long time Google user myself. But when it comes to angular, I think vuejs is just _more_ intuitive.

<3

**Comment by googl-github** [comment]
#5
